name: create_release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - 'README.md'
      - '.gitignore'
      - '.devcontainer'
      - '.vscode'
      - 'misc'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: rna_splice_tool
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: |
          docker run --entrypoint Rscript --rm rna_splice_tool -e "devtools::test()"

      - name: Check samtools installation
        run: |
          docker run --entrypoint samtools --rm rna_splice_tool --version"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create version
        id: create_version
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Update version in DESCRIPTION
        run: |
          sed -i -e "s/^Version: .*/Version: ${{ steps.create_version.outputs.tag }}/" DESCRIPTION

      - name: Build and push
        env:
          USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          REPOSITORY: cortar
          TAG_LATEST: latest
          TAG_SEMVER: ${{ steps.create_version.outputs.tag }}
          TAG_SHA: ${{ github.sha }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ env.TAG_LATEST }},
                ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ env.TAG_SEMVER }},
                ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ env.TAG_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create R package
        env:
          USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          REPOSITORY: cortar
          TAG_LATEST: latest
        run: |
          docker run -v $(pwd)/build:/build --entrypoint Rscript --rm ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ env.TAG_LATEST }} -e "devtools::build(path='/build')"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_version.outputs.tag }}
          files: build/*.tar.gz
          generate_release_notes: true
          token: ${{ github.token }}